### ISSUE TITLE
hello，I downloaded your project and found that it couldn't be opened

### ISSUE THREAD

**Issue by liming-xxw** [rchl/nuxt3-i18n#1]
![image](https://user-images.githubusercontent.com/56504602/168589364-6d6f149e-9d55-4f12-826b-a5c29971ae4e.png)
How to solve it
thank you

**Comment by rchl** [comment]
This is just some test project.
Try with https://github.com/nuxt-community/i18n-module/tree/next instead if you want to run nuxt 3 with nuxtjs-i18n module.

**Comment by liming-xxw** [comment]
谢谢
